"""empty message

Revision ID: 47263040317f
Revises: ab514bd6af0e
Create Date: 2026-01-01 14:30:50.299347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47263040317f'
down_revision = 'ab514bd6af0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.INTEGER(), nullable=True))

    op.drop_table('user')
    # ### end Alembic commands ###
